services:
  jupyter-openmoa:
    image: jupyter-openmoa:${OPENMOA_VERSION}
    ports:
      - "8888:8888"
    build:
      context: ../
      dockerfile: docker/dockerfile
      args:
        - OPENMOA_VERSION=${OPENMOA_VERSION}
